# permissions for end users to edit acrdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: acrdeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: acrops
    app.kubernetes.io/part-of: acrops
    app.kubernetes.io/managed-by: kustomize
  name: acrdeployment-editor-role
rules:
- apiGroups:
  - deployments.acrops.io
  resources:
  - acrdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.acrops.io
  resources:
  - acrdeployments/status
  verbs:
  - get
