---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - deployments.acrops.io
  resources:
  - azurecontainerregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.acrops.io
  resources:
  - azurecontainerregistries/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.acrops.io
  resources:
  - azurecontainerregistries/status
  verbs:
  - get
  - patch
  - update
