apiVersion: deployments.acrops.io/v1beta1
kind: ACRDaemonSet
metadata:
  labels:
    app.kubernetes.io/name: acrdaemonset
    app.kubernetes.io/instance: acrdaemonset-sample
    app.kubernetes.io/part-of: acrops
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: acrops
  name: acrdaemonset-sample
spec:
  image: acrName/image
  tag: prod 
  daemonset:
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      labels:
        app.kubernetes.io/name: acrdaemonset
        app.kubernetes.io/instance: daemonset-sample
        app.kubernetes.io/part-of: acrops
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/created-by: acrops
      name: acrdaemonset-sample
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: acrdaemonset
            app.kubernetes.io/instance: daemonset-sample
        template:
          metadata:
            labels:
              app.kubernetes.io/name: acrdaemonset
              app.kubernetes.io/instance: daemonset-sample
