# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/deployments.acrops.io_azurecontainerregistries.yaml
- bases/deployments.acrops.io_acrdeployments.yaml
- bases/deployments.acrops.io_acrdaemonsets.yaml
- bases/deployments.acrops.io_acrstatefulsets.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_azurecontainerregistries.yaml
#- path: patches/webhook_in_acrdeployments.yaml
#- path: patches/webhook_in_acrdaemonsets.yaml
#- path: patches/webhook_in_acrstatefulsets.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_azurecontainerregistries.yaml
#- path: patches/cainjection_in_acrdeployments.yaml
#- path: patches/cainjection_in_acrdaemonsets.yaml
#- path: patches/cainjection_in_acrstatefulsets.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
